FROM python:3.12-slim-bookworm

WORKDIR /app

# Install uv
RUN pip install --no-cache-dir uv

# Copy & install dependencies
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --system

COPY . .

RUN chmod +x entrypoint.sh

EXPOSE 5000

CMD ["./entrypoint.sh"]
